import { createPinia } from 'pinia'
export const pinia = createPinia()
export * from './modules/app'
export * from './modules/knowledge'
export * from './modules/note'
export * from './modules/schedule'
export * from './modules/history'
export * from './modules/settings'
export * from './modules/tabs'
export * from './modules/connection'
