name: happy_friday_android
description: Happy Friday Lite 安卓端 - 企业内网连接电脑端，按账号读取笔记与对话
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_secure_storage: ^9.2.0
  qr_code_scanner: ^1.0.1
  wake_on_lan: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
